[project]
name = "tl10k"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "edgartools>=3.11.1",
    "openai>=1.61.1",
]
